name: admin_package
description: A new Flutter package project.
version: 0.0.1
homepage: "null"
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_package:
    path: ../core_package
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: any
  json_annotation: any
  mocktail: ^0.3.0

dev_dependencies:
  authentication_package:
    path: ../authentication_package
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any

flutter: null
