name: core_package
description: A new Flutter package project.
version: 0.0.1
homepage: "no homepage"
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: any
  json_annotation: any
  logger: ^2.0.1
  pocketbase: ^0.15.0

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any

flutter: null
